name = input("what is your name?:")
age = int(input("how old are you?:"))
home = input("what is your addres?:")
hobby = input("what is your hobby?:")
surname = input("what is your surname?:")
print("my name is "  + name + " " + "my age is " + str(age) + " " + " and my surname is" + " " + surname + " " + "im living in" + " " + home + " " + "my hobby is" + " " + hobby)